# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    dynamodb_table = "my-lock-table"
    encrypt        = true
    key            = "vpc/terraform.tfstate"
    region         = "us-east-2"
    bucket         = "my-terraform-state-123612"
  }
}
